"""initial_migration

Revision ID: 62b9fe3dbf5e
Revises: 9d01d6aa5f02
Create Date: 2026-06-24 11:40:20.826385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '62b9fe3dbf5e'
down_revision: Union[str, None] = '9d01d6aa5f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_designations_id', table_name='designations')
    op.drop_table('designations')
    op.drop_index('ix_departments_id', table_name='departments')
    op.drop_index('name', table_name='departments')
    op.drop_table('departments')
    op.drop_table('purchase_order_items')
    op.drop_index('document_id', table_name='document_approvals')
    op.drop_index('ix_document_approvals_id', table_name='document_approvals')
    op.drop_table('document_approvals')
    op.drop_index('ix_leave_balances_id', table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index('ix_salary_components_id', table_name='salary_components')
    op.drop_table('salary_components')
    op.drop_table('purchase_request_items')
    op.drop_index('ix_self_assessments_id', table_name='self_assessments')
    op.drop_table('self_assessments')
    op.drop_index('ix_attendance_correction_requests_id', table_name='attendance_correction_requests')
    op.drop_table('attendance_correction_requests')
    op.drop_index('ix_evaluation_cycles_id', table_name='evaluation_cycles')
    op.drop_table('evaluation_cycles')
    op.create_foreign_key(None, 'employees', 'employees', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_table('evaluation_cycles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('period', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='evaluation_cycles_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_evaluation_cycles_id', 'evaluation_cycles', ['id'], unique=False)
    op.create_table('attendance_correction_requests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attendance_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correction_date', sa.DATE(), nullable=False),
    sa.Column('requested_check_in', mysql.DATETIME(), nullable=True),
    sa.Column('requested_check_out', mysql.DATETIME(), nullable=True),
    sa.Column('reason', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('reviewed_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewer_comment', mysql.TEXT(), nullable=True),
    sa.Column('reviewed_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], name='attendance_correction_requests_ibfk_2'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='attendance_correction_requests_ibfk_1'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name='attendance_correction_requests_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_attendance_correction_requests_id', 'attendance_correction_requests', ['id'], unique=False)
    op.create_table('self_assessments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('summary', mysql.TEXT(), nullable=False),
    sa.Column('achievements', mysql.TEXT(), nullable=True),
    sa.Column('challenges', mysql.TEXT(), nullable=True),
    sa.Column('goals', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('reviewed_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewer_comment', mysql.TEXT(), nullable=True),
    sa.Column('reviewed_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='self_assessments_ibfk_1'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name='self_assessments_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_self_assessments_id', 'self_assessments', ['id'], unique=False)
    op.create_table('purchase_request_items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('purchase_request_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estimated_price', mysql.FLOAT(), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='purchase_request_items_ibfk_2'),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['purchase_requests.id'], name='purchase_request_items_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('salary_components',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('component_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('is_recurring', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('effective_from', sa.DATE(), nullable=True),
    sa.Column('effective_to', sa.DATE(), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='salary_components_ibfk_2'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='salary_components_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_salary_components_id', 'salary_components', ['id'], unique=False)
    op.create_table('leave_balances',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leave_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quota', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='leave_balances_ibfk_2'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='leave_balances_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_leave_balances_id', 'leave_balances', ['id'], unique=False)
    op.create_table('document_approvals',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('reviewed_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewer_note', mysql.TEXT(), nullable=True),
    sa.Column('reviewed_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['employee_documents.id'], name='document_approvals_ibfk_1'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name='document_approvals_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_document_approvals_id', 'document_approvals', ['id'], unique=False)
    op.create_index('document_id', 'document_approvals', ['document_id'], unique=True)
    op.create_table('purchase_order_items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', mysql.FLOAT(), nullable=False),
    sa.Column('total_amount', mysql.FLOAT(), nullable=False),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='purchase_order_items_ibfk_2'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name='purchase_order_items_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('departments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], name='departments_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'departments', ['name'], unique=True)
    op.create_index('ix_departments_id', 'departments', ['id'], unique=False)
    op.create_table('designations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('department', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('level', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_designations_id', 'designations', ['id'], unique=False)
    # ### end Alembic commands ###
